/** 
* Copyright 2019 Liu Ziyi.
*/

/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_lifesense_sleep_score_LSSleepScore */

#ifndef _Included_com_lifesense_sleep_score_LSSleepScore
#define _Included_com_lifesense_sleep_score_LSSleepScore
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_lifesense_sleep_score_LSSleepScore
 * Method:    RateSleepQuality
 * Signature: (Lcom/lifesense/sleep_score/LSSleepScoreInput;)Lcom/lifesense/sleep_score/LSSleepScoreResult;
 */
JNIEXPORT jobject JNICALL Java_com_lifesense_sleep_1score_LSSleepScore_RateSleepQuality
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
